name: Deploy
permissions: write-all
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i pnpm -g
      - run: npm add vitepress

      - name: Build
        run: pnpm docs:build
        
      - name: Copy Logo
        run: cp logo.svg docs/.vitepress/dist/ -f
